---
- hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Create a resource group for our resources
      azure_rm_resourcegroup:
        name: AnsibleAzure01
        location: eastus
  
    - name: Create a VNet
      azure_rm_virtualnetwork:
        name: Vnet01
        resource_group: AnsibleAzure01
        address_prefixes:
          - "10.0.0.0/24"

    - name: Create a Subnet
      azure_rm_subnet:
        resource_group: AnsibleAzure01
        name: subnet001
        address_prefix: "10.0.0.0/24"
        virtual_network: Vnet01
    
    - name: Create Azure VM01
      azure_rm_virtualmachine:
        resource_group: AnsibleAzure01
        name: AAVM01
        vm_size: Standard_A1_v2
        os_type: Windows
        admin_username: 
        admin_password: 
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2016-Datacenter
          version: latest
        location: eastus