---
- hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Create a resource group for our resources
      azure_rm_resourcegroup:
        name: AnsibleAzure01
        location: eastus
  
    - name: Create a VNet
      azure_rm_virtualnetwork:
        name: Vnet01
        resource_group: AnsibleAzure01
        address_prefixes:
          - "10.0.0.0/24"

    - name: Create a Subnet
      azure_rm_subnet:
        resource_group: AnsibleAzure01
        name: subnet001
        address_prefix: "10.0.0.0/24"
        virtual_network: Vnet01
    
    - name: Create Azure VM01
      azure_rm_virtualmachine:
        resource_group: AnsibleAzure01
        name: AAVM01
        vm_size: Standard_A1_v2
        os_type: Windows
        admin_username: 
        admin_password: 
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2016-Datacenter
          version: latest
        location: eastus

    - name: Enable WinRM for Ansible
      azure_rm_virtualmachine_extension:
        name: winrmremoting
        resource_group: AnsibleAzure01
        virtual_machine_name: AAVM01
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: 1.9
        settings: '{
          "fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],
          "commandToExecute": "powershell.exe -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"
        }'
        auto_upgrade_minor_version: true
